@startuml "Bookstore Mamagement System"
hide circle
class "ผู้ผลิต"{

}
class "บุคคล"{

}
class "ระบบการจัดการร้านหนังสือ"{

}
class "เจ้าของร้าน"{

}
class "พนักงาน"{

}
class "ลูกค้า"{

}
"ระบบการจัดการร้านหนังสือ" o-- "บุคคล"
"บุคคล" o-- "เจ้าของร้าน"
"บุคคล" o-- "พนักงาน"
"บุคคล" o-- "ลูกค้า"
@enduml