@startuml "Bookstore Mamagement System"
skinparam classAttributeIconSize 0
hide circle
class "ผู้ผลิต"{
+ตำแหน่ง
-ชือ่
-นามสกุล
+บอกตำแหน่ง()
+บอกชื่อ()
+บอกนามสกุล()
}

class "ระบบการจัดการร้านหนังสือ"{

-ข้อมูลสินค้า
-ข้อมูลผู้ผลิต
-สั่งซื้อสินค้า
-ขายสินค้า
-ยอดขายสินค้า
-บันทึกข้อมูลสินค้าได้()
-บันทึกข้อมูลผู้ผลิตได้()
-ขายสินค้าได้()
-ดูสรุปยอดขายสินค้ารายเดือนได้

}
class "เจ้าของร้าน"{
+ตำแหน่ง
-ชือ่
-นามสกุล
+บอกตำแหน่ง()
-บอกชื่อ()
-บอกนามสกุล()
}
class "พนักงาน"{
+ตำแหน่ง
-ชือ่
-นามสกุล
+บอกตำแหน่ง()
-บอกชื่อ()
-บอกนามสกุล()
}
class "บุคคล"{
+ตำแหน่ง
-ชื่อ
-นามสกุล
}
class "ลูกค้า"{
-ชือ่
-นามสกุล
-บอกชื่อ()
-บอกนามสกุล()
}

class "จัดการข้อมูลสินค้า"{
+ชื่อสินค้า
+ประเภทสินค้า
+บันทึกข้อมูลชื่อสินค้า()
+บันทึกข้อมูลประเภทสินค้า()
}
class "จัดเก็บข้อมูลผู้ผลิต"{
-ชื่อ
-ข้อมูลสินค้า
-บันทึกชื่อผู้ผลิต()
-บันทึกข้อมูลสินค้า()
}
class "สั่งซื้อสินค้า"{
-ตัวแทนจัดจำหน่าย
-สินค้า
-เบอร์โทร

}
class "รับสินค้า"{
-ตรวจสอบสินค้า
-ความถูกต้องสินค้า()
}
class "สินค้า"{
+ราคา
+จำนวนสินค้า
+ใบเสร็จ
+บอกราคา()
+บอกจำนวนสินค้า()
+ออกใบเสร็จรับเงิน()

}
class "รายงานสรุปยอดขาย"{
-สรุปยอดขาย
-บอกยอดขายประจำเดือน()
}
class "ใบสั่งซื้อ"{
+สินค้า
+กำหนดสั่งซื้อ
+รายละเอียดสินค้า()
+ผู้สั่งซื้อ()d
+ปรินใบสั่งซื้อ()
}
class "ค้นหาสินค้า"{
+ชื่อสินค้า
+จำนวนสินค้า
+ราคา
+ชื่อสินค้า()
+จำนวนสินค้า()
+ราคา()
+ต้อการซื้อสินค้า()
}

class "ใบเสร็จ"{
+ชื่อสินค้า
+ราคา
+แสดงชื่อสินค้า()
+แสดงราคาสินค้า()
+ปรินใบเสร็จ()
}
class "ตรวจสอบสินค้า"{
+ชื่อสินค้า
+ราคา
+หมวด
+ตรวจสอบชื่อสินค้า()
+ตรวจสอบราคา()
+ตรวจสอบหมวด()
+รับสินค้า()
+ไม่รับสินค่า()
}
class "ผู้ผลิตสินค้า"{
+ชื่อสินค้า
+จำนวนสินค้า
+เบอร์โทร
+ระบุชื่อสินค้า()
+ระบุจำนวนสินค้า()
+ระบุแสดงเบอร์โทร()
}
"บุคคล" <|-- "พนักงาน"
"บุคคล" <|-- "เจ้าของร้าน"
"บุคคล" <|-- "ผู้ผลิต"
"บุคคล" <|-- "ลูกค้า"
"ระบบการจัดการร้านหนังสือ" o-- "1..n""บุคคล" 
"ระบบการจัดการร้านหนังสือ" o-- "1..n""ตรวจสอบสินค้า" 
"ระบบการจัดการร้านหนังสือ" o-- "1..n""จัดเก็บข้อมูลผู้ผลิต"
"ระบบการจัดการร้านหนังสือ" o-- "1..n""สั่งซื้อสินค้า"
"ระบบการจัดการร้านหนังสือ" o-- "สินค้า"
"ระบบการจัดการร้านหนังสือ" o-- "รายงานสรุปยอดขาย"
"สั่งซื้อสินค้า" *-- "ผู้ผลิตสินค้า"
"ผู้ผลิตสินค้า" *-- "ใบสั่งซื้อ"
"ใบสั่งซื้อ" *-- "รับสินค้า"
"สินค้า" *--"ค้นหาสินค้า"
"ค้นหาสินค้า" *-- "ใบเสร็จ"
"ลูกค้า" -left-* "1..n""สินค้า": ซื้อ
"พนักงาน" --* "ตรวจสอบสินค้า":ทำการ
"ตรวจสอบสินค้า" --* "จัดการข้อมูลสินค้า"
"เจ้าของร้าน" -right-* "รายงานสรุปยอดขาย":ดู
"ผู้ผลิต" -right-* "ใบสั่งซื้อ": รับ
@enduml