@startuml "Bookstore Mamagement System"
skinparam classAttributeIconSize 0
hide circle
class "ผู้ผลิต"{
+ตำแหน่ง
-ชือ่
-นามสกุล
+บอกตำแหน่ง()
+บอกชื่อ()
+บอกนามสกุล()
}

class "ระบบการจัดการร้านหนังสือ"{

-ข้อมูลสินค้า
-ข้อมูลผู้ผลิต
-สั่งซื้อสินค้า
-ขายสินค้า
-ยอดขายสินค้า
-บันทึกข้อมูลสินค้าได้()
-บันทึกข้อมูลผู้ผลิตได้()
-สั่งซื้อสินค้าได้
-ขายสินค้าได้()
-ดูสรุปยอดขายสินค้ารายเดือนได้

}
class "เจ้าของร้าน"{
+ตำแหน่ง
-ชือ่
-นามสกุล
+บอกตำแหน่ง()
+บอกชื่อ()
+บอกนามสกุล()
}
class "พนักงาน"{
+ตำแหน่ง
-ชือ่
-นามสกุล
+บอกตำแหน่ง()
+บอกชื่อ()
+บอกนามสกุล()
}
class "บุคคล"{

}
class "ลูกค้า"{
-ชือ่
-นามสกุล
+บอกชื่อ()
+บอกนามสกุล()
}

class "จัดการข้อมูลสินค้า"{

}
class "จัดเก็บข้อมูลผู้ผลิต"{

}
class "สั่งซื้อสินค้า"{

}
class "รับสินค้า"{

}
class "ขายสินค้า"{

}
class "ออกรายงานสรุปยอดขาย"{

}
class "ออกใบสั่งซื้อ"{

}
class "ค้นหาสินค้า"{

}
class "ขายสินค้า"{

}
class "ตรวจสอบสินค้า"{

}
class "ใบเสร็จ"{

}
"บุคคล" o-- "พนักงาน"
"บุคคล" o-- "เจ้าของร้าน"
"บุคคล" o-- "ผู้ผลิต"
"บุคคล" o-- "ลูกค้า"
"ระบบการจัดการร้านหนังสือ" o-- "บุคคล" 
"ระบบการจัดการร้านหนังสือ" o-- "จัดการข้อมูลสินค้า" 
"ระบบการจัดการร้านหนังสือ" o-- "จัดเก็บข้อมูลผู้ผลิต"
"ระบบการจัดการร้านหนังสือ" o-- "สั่งซื้อสินค้า"
"ระบบการจัดการร้านหนังสือ" o-- "ขายสินค้า"
"ระบบการจัดการร้านหนังสือ" o-- "ออกรายงานสรุปยอดขาย"
"สั่งซื้อสินค้า" o-- "ออกใบสั่งซื้อ"
"จัดการข้อมูลสินค้า" o-- "ตรวจสอบสินค้า"
"ออกใบสั่งซื้อ" o-- "รับสินค้า"
"ขายสินค้า" o--"ค้นหาสินค้า"
"ค้นหาสินค้า" o-- "ใบเสร็จ"
@enduml