@startuml "สั่งซื้อสินค้า"
actor "พนักงาน"
participant "สั่งซื้อสินค้า"
participant "ผู้ผลิตสินค้า"
participant "ใบสั่งซื้อ"
participant "รับสินค้า"
actor "ผู้ผลิต"
"พนักงาน" --> "สั่งซื้อสินค้า":สินค้าหมด
"สั่งซื้อสินค้า" --> "ใบสั่งซื้อ":ค้นหา
"ใบสั่งซื้อ" --> "ผู้ผลิตสินค้า"
"ผู้ผลิตสินค้า" --> "ผู้ผลิต":สั่งซื้อสินค้า
"ผู้ผลิต" --> "รับสินค้า": ส่งสินค้า

@enduml