@startuml "Bookstore Mamagement System"
skinparam packageStyle rectangle

:ผู้ผลิต: as Manufacturer
:เจ้าของร้าน: as Admin
:ลูกค้า: as Customer
:พนักงาน: as Staff
rectangle "Bookstore Mamagement System"{
Staff -right- (จัดการข้อมูลสินค้า)
(จัดการข้อมูลสินค้า) <-- (เก็บข้อมูล)
(เก็บข้อมูล) <-- (ฐานข้อมูล)
Staff -- (จัดเก็บข้อมูลผู้ผลิต)
(จัดเก็บข้อมูลผู้ผลิต) <-- (ฐานข้อมูล)
Admin -left- (ออกรายงานสรุปยอดขายรายเดือน)
(ออกรายงานสรุปยอดขายรายเดือน) <-- (ฐานข้อมูล)
Customer -left- (แสดงความต้องการซื้อ)
Staff -right-(ค้นหาข้อมูลสินค้า)
(แสดงความต้องการซื้อ) --> (ค้นหาข้อมูลสินค้า)
(ค้นหาข้อมูลสินค้า) <-- (ฐานข้อมูล)
(ค้นหาข้อมูลสินค้า) <-- (ขายสินค้า)
(จัดการข้อมูลสินค้า) <-- (สั่งซื้อสินค้า)
(สั่งซื้อสินค้า) <-- (ออกใบสั่งซื้อ)
Manufacturer -right- (รับสินค้า)
Staff -right- (ตรวจสอบสินค้า)
(ตรวจสอบสินค้า) --> (รับสินค้า)
(ตรวจสอบสินค้า) <-left- (จัดการข้อมูลสินค้า)
}
@enduml