@startuml Bookstore_Mamagement_System
skinparam packageStyle rectangle
:ผู้ผลิต: as Manufacturer
:เจ้าของร้าน: as Admin
:ลูกค้า: as Customer
:พนักงาน: as Staff
rectangle Bookstore_Mamagement_System{


Staff -left- (ตรวจสอบสินค้าในคลัง)
(ตรวจสอบสินค้าในคลัง) <-- (จดบันทึกลงสมุด)
(จดบันทึกลงสมุด) <-- (บันทึกลงฐานข้อมูล)
Staff -left- (ตรวจสอบข้อมูลผู้ผลิต)
(ตรวจสอบข้อมูลผู้ผลิต) <-- (บันทึกลงฐานข้อมูล)
Admin -left- (ตรวจสอบยอดขายสินค้า)
Customer -right- (แสดงความต้องการซื้อ)
Staff -left- (ค้นหาข้อมูลสินค้า)
(ค้นหาข้อมูลสินค้า) <-- (มีสินค้า)
(ค้นหาข้อมูลสินค้า) <-- (ไม่มีสินค้า)
(มีสินค้า) <-- (แสดงข้อมูลสินค้า)
(แสดงความต้องการซื้อ) <-- (ค้นหาข้อมูลสินค้า)
(ไม่มีสินค้า) <-- (สั่งซื้อสินค้า)
(แสดงข้อมูลสินค้า) <-- (ขายสินค้า)
(ตรวจสอบสินค้าในคลัง) <-- (สินค้าไม่เพี่ยงพอ)
(สินค้าไม่เพี่ยงพอ) <-- (สั่งซื้อสินค้า)
(สั่งซื้อสินค้า) <-- (ค้นหาผู้ผลิด)
(ค้นหาผู้ผลิด) <-- (โทรสั่งซื้อสินค้า)
(โทรสั่งซื้อสินค้า) <-- (ออกใบสั่งซื้อสินค้า)
(Manufacturer) -left- (ส่งสินค้า)
(ส่งสินค้า) <-- (ตรวจสอบสินค้า)
Staff -- (ตรวจสอบสินค้า)
(ตรวจสอบสินค้า) <-- (สินค้าถูกต้อง)
(ตรวจสอบสินค้า) <-- (สินค้าไม่ถูกต้อง)
(สินค้าถูกต้อง) <-- (รับสินค้า)
(สินค้าไม่ถูกต้อง) <-- (เขียนไว่ในใบสั่งซื้อ)
(ตรวจสอบยอดขายสินค้า) <-- (ฐานข้อมูล)
(ฐานข้อมูล) <-- (บันทึกลงฐานข้อมูล)
}
@enduml